// src/components/Biography.vue
<template>
  <div class="bio container mt-5" id="bio">
    <h1 class="d-flex justify-content-end bold">Bio</h1>
    <div class="row">
      <!-- Imagen -->
      <div class="col-12 col-md-4 mb-5">
        <div class="photo-frame">
          <span class="photo-halo" aria-hidden="true"></span>
          <div class="photo-mask">
            <img :src="image" alt="Photo of {{ name }}" class="photo-image" />
          </div>
        </div>
      </div>
      <!-- Información -->
      <div class="col-12 col-md-8 d-flex flex-column justify-content-center">
        <h2 class="medium">{{ name }}</h2>
        <h3 class="light fs-5">{{ occupation }}</h3>
        <p class="medium">{{ bio }}</p>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "Biography",
  data() {
    return {
      image: "https://curriculum-pages.vercel.app/assets/profile-I6UqGaSy.png",
      name: "Joaquin Gonzalez",
      occupation: "Web Developer",
      bio: "¡Hola! Soy Joaquin Gonzalez, y me encanta el desarrollo web. Me especializo en JavaScript y React, y actualmente me dedico a crear encuestas con LimeSurvey, donde disfruto transformando ideas en soluciones prácticas y efectivas.\n\nSiempre estoy buscando aprender algo nuevo. Ahora, me estoy sumergiendo en un bootcamp de front end para mejorar mis habilidades y poder ofrecer soluciones completas en mis proyectos. Mi objetivo es seguir creciendo como desarrollador web, abarcando tanto el frontend como el backend.\n\nMe apasiona resolver desafíos técnicos y ver cómo mis proyectos cobran vida en la web.",
      email: "jg.cabello@icloud.com",
    };
  },
};
</script>

<style scoped>
h1,
h2,
h3 {
  margin-bottom: 15px;
}

.photo-frame {
  position: relative;
  width: min(100%, 320px);
  aspect-ratio: 1 / 1;
  margin: 0 auto;
  padding: 14px;
}

.photo-halo {
  position: absolute;
  inset: 10% 8% 8% 8%;
  border-radius: 28px;
  background:
    radial-gradient(
      circle at 50% 45%,
      rgba(0, 207, 255, 0.42),
      transparent 56%
    ),
    radial-gradient(
      circle at 52% 55%,
      rgba(37, 99, 235, 0.34),
      transparent 68%
    ),
    radial-gradient(
      circle at 50% 50%,
      rgba(139, 92, 246, 0.18),
      transparent 72%
    );
  filter: blur(24px);
  opacity: 0.95;
}

.photo-mask {
  position: relative;
  width: 100%;
  height: 100%;
  overflow: hidden;
  border-radius: 28px;
  border: 1px solid rgba(229, 231, 235, 0.14);
  background: linear-gradient(
    180deg,
    rgba(17, 24, 39, 0.9),
    rgba(10, 10, 15, 0.92)
  );
  box-shadow:
    0 24px 70px rgba(0, 0, 0, 0.36),
    0 0 0 1px rgba(0, 207, 255, 0.12),
    0 0 48px rgba(0, 207, 255, 0.22);
}

.photo-mask::after {
  content: "";
  position: absolute;
  inset: 0;
  background:
    radial-gradient(
      circle at center,
      transparent 58%,
      rgba(10, 10, 15, 0.08) 72%,
      rgba(10, 10, 15, 0.55) 100%
    ),
    linear-gradient(
      180deg,
      rgba(255, 255, 255, 0.04),
      transparent 26%,
      transparent 74%,
      rgba(255, 255, 255, 0.03)
    );
  pointer-events: none;
}

.photo-image {
  width: 100%;
  height: 100%;
  object-fit: cover;
  object-position: center;
  display: block;
  transform: scale(1.02);
  filter: saturate(1.05) contrast(1.02);
}

@media (max-width: 767.98px) {
  .photo-frame {
    width: min(100%, 280px);
    padding: 12px;
  }
}

a {
  text-decoration: none;
  color: var(--color-text);
  transition: color 0.3s ease-in-out;
}
</style>

// src/components/Biography.jsx
const image = 'https://curriculum-pages.vercel.app/assets/profile-I6UqGaSy.png'

export default function Biography() {
  return (
    <section
      className="flex flex-col lg:flex-row items-center justify-between min-h-screen gap-12 py-32 px-5 md:px-16 max-w-[1200px] mx-auto"
      id="hero"
    >
      {/* Text */}
      <div className="w-full lg:w-3/5 text-center lg:text-left" data-usal="fade-r duration-700">
        <span
          className="text-secondary mb-4 inline-block tracking-[0.2em] text-xs font-bold uppercase"
          style={{ fontFamily: '"Hanken Grotesk", sans-serif' }}
        >
          FRONT-END DEVELOPER
        </span>

        <h1
          className="gradient-text mb-6 text-4xl md:text-6xl font-bold"
          style={{ fontFamily: '"Geist", sans-serif', letterSpacing: '-0.04em', lineHeight: 1.1 }}
        >
          Construyendo el futuro de la web con elegancia técnica.
        </h1>

        <p
          className="text-on-surface-variant mb-10 max-w-2xl mx-auto lg:mx-0 text-lg leading-relaxed"
          style={{ fontFamily: '"Hanken Grotesk", sans-serif' }}
        >
          Hola, soy Joaquín. Me especializo en crear interfaces fluidas y reactivas usando{' '}
          <strong className="text-on-surface">Vue 3</strong>,{' '}
          <strong className="text-on-surface">React</strong> y{' '}
          <strong className="text-on-surface">JavaScript</strong> moderno. Mi enfoque combina
          la precisión del código con una estética visual pulida.
        </p>

        <div className="flex flex-wrap justify-center lg:justify-start gap-4">
          <a
            href="#proyectos"
            className="flex items-center gap-2 px-8 py-3 rounded-lg font-bold text-on-primary-container transition-transform hover:scale-105"
            style={{ background: '#2563eb', fontFamily: '"Hanken Grotesk", sans-serif' }}
          >
            Ver proyectos
            <span className="material-symbols-outlined text-[1.1rem]">arrow_downward</span>
          </a>
          <a
            href="#contacto"
            className="border border-primary text-primary px-8 py-3 rounded-lg font-bold hover:bg-primary/10 transition-colors"
            style={{ fontFamily: '"Hanken Grotesk", sans-serif' }}
          >
            Contacto
          </a>
        </div>
      </div>

      {/* Photo */}
      <div className="w-full lg:w-2/5 flex justify-center lg:justify-end" data-usal="fade-l duration-700 delay-200">
        <div className="relative w-64 h-64 md:w-80 md:h-80">
          {/* Glow */}
          <div
            className="absolute inset-0 rounded-full opacity-20 animate-pulse"
            style={{ background: 'radial-gradient(circle, #b4c5ff, #a0e4ff)', filter: 'blur(24px)' }}
          />
          {/* Photo frame */}
          <div className="glass-card relative w-full h-full rounded-full border-2 border-outline-variant/30 p-2 overflow-hidden">
            <img
              src={image}
              alt="Joaquín González"
              className="w-full h-full object-cover rounded-full"
            />
          </div>
          {/* Available badge */}
          <div className="glass-card absolute -bottom-4 -right-4 px-4 py-3 rounded-xl flex items-center gap-3">
            <div className="w-2.5 h-2.5 bg-green-400 rounded-full animate-pulse" />
            <span className="text-xs font-medium text-on-surface" style={{ fontFamily: '"JetBrains Mono", monospace' }}>
              Disponible para proyectos
            </span>
          </div>
        </div>
      </div>
    </section>
  )
}
